name: Lint Code

on:
  - pull_request

jobs:
  actionlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint GitHub Actions Workflow Files
        uses: docker://rhysd/actionlint:1.6.27
        with:
          args: -color
  yamllint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5 # Uses .python-version
      - name: Install yamllint
        run: |
          pip install --upgrade pip
          pip install yamllint
      - name: Lint YAML Files
        run: |
          yamllint .
  ruff:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5 # Uses .python-version
      - name: Install ruff
        run: |
          pip install --upgrade pip
          pip install ruff
      - name: Lint Python Files
        run: |
          ruff check --select I --output-format "github"
          ruff check --output-format "github"
